spring:
  application:
    name: shop
  datasource:
    url: jdbc:mysql://localhost:3306/shoes_shop
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: mail-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      user-signup-success: user.signup.success

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenhuy24112003@gmail.com
    password: thinvpctpompstgv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

lockout:
  attempts-cycle: 3
  temporary-lock: 1
  permanent-cycles: 2

redis:
  host: localhost
  port: 6379
  password: Aa@123456

cloudinary:
  cloud-name: dxsq3ivxs
  api-key: 393271661348597
  api-secret: 2uoNOu66wnJLU8utPTSTKV26IWk
  folder: shop/products

jwt:
  expiration:         # 1 * 24 * 60 * 60 = giay
    access: 3600      #      1 * 60 * 60 = 1 ngay = 3600 giay
    refresh: 2592000  #30 * 24 * 60 * 60 = 30 ngay = 2592000 giay
  secret-key: ctBoMlFyWkcFbOjvsTgFuCMqHn0Jx43bUzXUxXebVRE=

vnpay:
  #pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  #return-url: "http://localhost:3000/payment/payment-callback"
  #tmn-code: "PVJEHFHN"
  #secret-key: "K96600JY6WV85L5ZJF5TN8OFW2ZB8G2H"
  #api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "https://ae81f812bbc4.ngrok-free.app/payments/vnpay-return"
  tmn-code: "PMVJF3VN"
  secret-key: "WYOBEV6PUO63AWKQTNJPQ7FTLM4A8KNI"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

momo:
  end-point: "https://test-payment.momo.vn/v2/gateway/api"
  return-url: "http://localhost:3000/payment/payment-callback"
  ipn-url: "http://localhost:8080/payment/momo/ipn-handler"
  partner-code: "MOMOLRJZ20181206"
  access-key: "mTCKt9W3eU1m39TW"
  secret-key: "SetA5RDnLHvt51AULf51DyauxUo3kDU6"
